# Generated by Django 5.2.17 on 2026-08-25 07:36

import apps.accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "администратор платформы"),
                            ("owner", "владелец организации"),
                            ("admin", "администратор"),
                            ("teacher", "педагог"),
                            ("parent", "родитель"),
                            ("student", "ученик"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="роль",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
            ],
            options={
                "verbose_name": "роль в организации",
                "verbose_name_plural": "роли в организациях",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorDevice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "secret",
                    models.CharField(max_length=64, verbose_name="секрет (base32)"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="подтверждено"),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_used_counter",
                    models.BigIntegerField(
                        default=0, verbose_name="последний использованный шаг"
                    ),
                ),
                (
                    "recovery_codes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="резервные коды (хэши)"
                    ),
                ),
            ],
            options={
                "verbose_name": "второй фактор",
                "verbose_name_plural": "вторые факторы",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="телефон"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=80, verbose_name="фамилия"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=80, verbose_name="имя"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="отчество"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="доступ в админку Django"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="последняя активность"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
