# Generated by Django 5.2.17 on 2026-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=60, verbose_name="логин"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username", ""), _negated=True),
                fields=("username",),
                name="user_username_unique_not_blank",
            ),
        ),
    ]
