# Generated by Django 5.2.17 on 2026-08-25 07:36

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(max_length=60, unique=True, verbose_name="код"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="юридическое наименование",
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                (
                    "ogrnip",
                    models.CharField(blank=True, max_length=15, verbose_name="ОГРНИП"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=32, verbose_name="телефон"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="адрес"),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Telegram chat_id для заявок",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=apps.core.models._timezone_choices,
                        default="Asia/Krasnoyarsk",
                        max_length=64,
                        verbose_name="часовой пояс",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "module_max_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="максимум баллов за модуль",
                    ),
                ),
                (
                    "lesson_max_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=5,
                        verbose_name="максимум баллов за одно занятие",
                    ),
                ),
                (
                    "grade_backdate_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        verbose_name="на сколько дней назад можно выставлять баллы",
                    ),
                ),
                (
                    "data_retention_days",
                    models.PositiveIntegerField(
                        default=1095,
                        verbose_name="срок хранения персональных данных после отчисления, дней",
                    ),
                ),
                (
                    "lead_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        verbose_name="срок хранения необработанных заявок, дней",
                    ),
                ),
                (
                    "price_full_month",
                    models.PositiveIntegerField(
                        default=70000, verbose_name="цена полного формата, ₽/мес"
                    ),
                ),
                (
                    "price_career",
                    models.PositiveIntegerField(
                        default=0, verbose_name="цена профориентации, ₽"
                    ),
                ),
                (
                    "tutors_reference_price",
                    models.PositiveIntegerField(
                        default=88000,
                        verbose_name="справочный счёт за репетиторов, ₽/мес",
                    ),
                ),
                (
                    "tutors_reference_note",
                    models.CharField(
                        default="2 занятия в неделю × 4 предмета × 1 100 ₽",
                        max_length=200,
                        verbose_name="расчёт справочного счёта",
                    ),
                ),
            ],
            options={
                "verbose_name": "организация",
                "verbose_name_plural": "организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "host",
                    models.CharField(
                        db_index=True, max_length=253, unique=True, verbose_name="хост"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="основной"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "домен организации",
                "verbose_name_plural": "домены организаций",
                "ordering": ["-is_primary", "host"],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="на кого распространяется",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("pdn", "обработка персональных данных"),
                            ("minor_pdn", "обработка данных несовершеннолетнего"),
                            ("marketing", "информационные рассылки"),
                            ("cookie", "необязательные cookie"),
                        ],
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(max_length=32, verbose_name="версия документа"),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дано"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="отозвано"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="user-agent"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "согласие",
                "verbose_name_plural": "согласия",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "consent_type", "-granted_at"],
                        name="core_consen_organiz_f049f8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="кто (снимок)"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "вход в систему"),
                            ("login_failed", "неудачный вход"),
                            ("logout", "выход"),
                            ("view_student", "просмотр карточки ученика"),
                            ("view_lead", "просмотр заявки"),
                            ("grade_changed", "изменение оценки"),
                            ("grade_deleted", "удаление оценки"),
                            ("export", "экспорт данных"),
                            ("permission_changed", "изменение прав"),
                            ("consent_granted", "согласие получено"),
                            ("consent_revoked", "согласие отозвано"),
                            ("data_purged", "удаление по истечении срока хранения"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="действие",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="тип объекта"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="id объекта"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="user-agent"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="подробности"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="когда",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись журнала доступа",
                "verbose_name_plural": "журнал доступа к данным",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="core_auditl_organiz_e98001_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_auditl_action_d80c2d_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="core_auditl_object__42e4a9_idx",
                    ),
                ],
            },
        ),
    ]
