# Generated by Django 5.2.17 on 2026-08-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="расчётный счёт"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_bik",
            field=models.CharField(blank=True, max_length=9, verbose_name="БИК"),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_corr_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="корреспондентский счёт"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="банк"),
        ),
    ]
