# Generated by Django 5.2.17 on 2026-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organization_bank_account_organization_bank_bik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="price_entry_year",
            field=models.PositiveIntegerField(
                default=15000, verbose_name="вступительный взнос, ₽/год"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="price_mentor_month",
            field=models.PositiveIntegerField(
                default=30000,
                verbose_name="наставник, профориентация и подготовка к поступлению, ₽/мес",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="price_program_month",
            field=models.PositiveIntegerField(
                default=40000,
                verbose_name="образовательная программа и подготовка к аттестации, ₽/мес",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="price_career",
            field=models.PositiveIntegerField(
                default=0, verbose_name="цена профориентации отдельно, ₽"
            ),
        ),
    ]
