# Generated by Django 5.2.17 on 2026-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_organization_price_entry_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="hero_kicker",
            field=models.CharField(
                default="Семейный класс «Твёрдый знак» · Красноярск · 8–11 класс",
                max_length=200,
                verbose_name="надзаголовок на первом экране",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hero_lead",
            field=models.TextField(
                default="Подросток учится модулями по 5 недель, видит свою дорожную карту и получает баллы за конкретную работу. Вы видите то же, что и он.",
                verbose_name="лид на первом экране",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="hero_title",
            field=models.CharField(
                default="Вся учёба, аттестация и наставник — в одном месте",
                help_text="Коротко: шрифт заголовка рендерит строчные капителью, и длинный текст в три строки выглядит тяжело.",
                max_length=120,
                verbose_name="заголовок на первом экране",
            ),
        ),
    ]
