# Generated by Django 5.2.17 on 2026-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_organization_hero_kicker_organization_hero_lead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "вход в систему"),
                    ("login_failed", "неудачный вход"),
                    ("logout", "выход"),
                    ("view_student", "просмотр карточки ученика"),
                    ("view_lead", "просмотр заявки"),
                    ("grade_changed", "изменение оценки"),
                    ("grade_deleted", "удаление оценки"),
                    ("export", "экспорт данных"),
                    ("permission_changed", "изменение прав"),
                    ("consent_granted", "согласие получено"),
                    ("consent_revoked", "согласие отозвано"),
                    ("data_purged", "удаление по истечении срока хранения"),
                    ("two_factor_reset", "сброс второго фактора"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="действие",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="hero_title",
            field=models.CharField(
                default="Вся учёба — в одном месте",
                help_text="Коротко: шрифт заголовка рендерит строчные капителью, и длинный текст в три строки выглядит тяжело.",
                max_length=120,
                verbose_name="заголовок на первом экране",
            ),
        ),
    ]
