# Generated by Django 5.2.17 on 2026-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_auditlog_action_alter_organization_hero_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="schedule_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="ссылка на файл с расписанием"
            ),
        ),
    ]
