# Generated by Django 5.2.17 on 2026-08-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "вход в систему"),
                    ("login_failed", "неудачный вход"),
                    ("logout", "выход"),
                    ("view_student", "просмотр карточки ученика"),
                    ("view_lead", "просмотр заявки"),
                    ("grade_changed", "изменение оценки"),
                    ("grade_deleted", "удаление оценки"),
                    ("export", "экспорт данных"),
                    ("permission_changed", "изменение прав"),
                    ("consent_granted", "согласие получено"),
                    ("consent_revoked", "согласие отозвано"),
                    ("data_purged", "удаление по истечении срока хранения"),
                    ("two_factor_reset", "сброс второго фактора"),
                    ("password_changed", "смена пароля"),
                    ("plan_imported", "загрузка тематического планирования"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="действие",
            ),
        ),
    ]
