# Generated by Django 5.2.17 on 2026-08-25 07:36

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                ("title", models.CharField(max_length=20, verbose_name="учебный год")),
                ("starts_on", models.DateField(verbose_name="начало")),
                ("ends_on", models.DateField(verbose_name="конец")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="текущий"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "учебный год",
                "verbose_name_plural": "учебные годы",
                "ordering": ["-starts_on"],
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Основная шкала", max_length=80, verbose_name="название"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=True, verbose_name="по умолчанию"),
                ),
                (
                    "module_max_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        verbose_name="максимум за модуль",
                    ),
                ),
                (
                    "pass_from",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        max_digits=5,
                        verbose_name="зачёт от",
                    ),
                ),
                (
                    "base_from",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        max_digits=5,
                        verbose_name="базовый уровень от",
                    ),
                ),
                (
                    "elevated_from",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("70.00"),
                        max_digits=5,
                        verbose_name="повышенный уровень от",
                    ),
                ),
                (
                    "advanced_from",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        max_digits=5,
                        verbose_name="продвинутый уровень от",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_scales",
                        to="journal.academicyear",
                        verbose_name="учебный год",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "шкала оценивания",
                "verbose_name_plural": "шкалы оценивания",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="название")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("family_class", "семейный класс"),
                            ("club", "клуб самоопределения"),
                        ],
                        default="family_class",
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(11),
                        ],
                        verbose_name="класс",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="journal.academicyear",
                        verbose_name="учебный год",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "группа",
                "verbose_name_plural": "группы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("module", "учебный модуль"),
                            ("vacation", "каникулярная неделя"),
                        ],
                        default="module",
                        max_length=10,
                        verbose_name="тип",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="номер")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="тема"),
                ),
                (
                    "focus",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="смысловой фокус"
                    ),
                ),
                ("starts_on", models.DateField(verbose_name="начало")),
                ("ends_on", models.DateField(verbose_name="конец")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="journal.academicyear",
                        verbose_name="учебный год",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "модуль",
                "verbose_name_plural": "модули",
                "ordering": ["starts_on"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="начало")),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=45, verbose_name="длительность, мин"
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="тема занятия"
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(default=False, verbose_name="с оцениванием"),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="аудитория"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="journal.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="journal.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "занятие",
                "verbose_name_plural": "занятия",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lesson", "занятие"),
                            ("homework", "домашняя работа"),
                            ("quiz", "проверочная работа"),
                            ("test", "контрольная работа"),
                            ("credit", "зачёт"),
                        ],
                        max_length=20,
                        verbose_name="тип работы",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="название"
                    ),
                ),
                (
                    "max_points",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="максимум баллов"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="дата"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="порядок"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_items",
                        to="journal.group",
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_item",
                        to="journal.lesson",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_items",
                        to="journal.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "элемент оценивания",
                "verbose_name_plural": "элементы оценивания",
                "ordering": ["position", "due_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_name", models.CharField(max_length=80, verbose_name="фамилия")),
                ("first_name", models.CharField(max_length=80, verbose_name="имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="отчество"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=16, verbose_name="телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "extra_contacts",
                    apps.core.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="дополнительные контакты"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="учётная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "родитель",
                "verbose_name_plural": "родители",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_name", models.CharField(max_length=80, verbose_name="фамилия")),
                ("first_name", models.CharField(max_length=80, verbose_name="имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="отчество"
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(11),
                        ],
                        verbose_name="класс",
                    ),
                ),
                (
                    "birth_date",
                    apps.core.fields.EncryptedDateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
                (
                    "document_info",
                    apps.core.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="документ"
                    ),
                ),
                (
                    "attestation_partner",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="аккредитованная школа-партнёр для аттестации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "учится"),
                            ("on_hold", "приостановлено"),
                            ("graduated", "выпустился"),
                            ("left", "ушёл"),
                        ],
                        db_index=True,
                        default="enrolled",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "enrolled_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата зачисления"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="заметка")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="учётная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "ученик",
                "verbose_name_plural": "ученики",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="назначение")),
                ("period_start", models.DateField(verbose_name="период с")),
                ("period_end", models.DateField(verbose_name="период по")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="сумма, ₽"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "предстоит"),
                            ("paid", "оплачено"),
                            ("cancelled", "отменено"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                (
                    "due_on",
                    models.DateField(blank=True, null=True, verbose_name="оплатить до"),
                ),
                (
                    "paid_on",
                    models.DateField(blank=True, null=True, verbose_name="оплачено"),
                ),
                (
                    "provider",
                    models.CharField(
                        default="manual", max_length=40, verbose_name="способ"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="id платежа у провайдера",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто отметил",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="journal.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "оплата",
                "verbose_name_plural": "оплаты",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="день"
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "тяжело"),
                            (2, "трудновато"),
                            (3, "ровно"),
                            (4, "хорошо"),
                            (5, "отлично"),
                        ],
                        verbose_name="состояние",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, verbose_name="комментарий ученика"),
                ),
                (
                    "mentor_feedback",
                    models.TextField(
                        blank=True, verbose_name="обратная связь наставника"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to="journal.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "отметка состояния",
                "verbose_name_plural": "индикатор состояния",
                "ordering": ["-day"],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "joined_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="зачислен в группу",
                    ),
                ),
                (
                    "left_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="выбыл из группы"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="journal.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="journal.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "состав группы",
                "verbose_name_plural": "составы групп",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                related_name="groups",
                through="journal.GroupMembership",
                to="journal.student",
                verbose_name="состав",
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="баллы",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="комментарий педагога"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="когда выставлено",
                    ),
                ),
                (
                    "given_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто выставил",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "grade_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="journal.gradeitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="journal.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "балл",
                "verbose_name_plural": "баллы",
                "ordering": ["-graded_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "relation",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="кем приходится"
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(default=False, verbose_name="основной контакт"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="journal.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to="journal.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "связь ребёнок — родитель",
                "verbose_name_plural": "связи ребёнок — родитель",
            },
        ),
        migrations.AddField(
            model_name="parent",
            name="students",
            field=models.ManyToManyField(
                related_name="parents",
                through="journal.StudentParent",
                to="journal.student",
                verbose_name="дети",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="предмет")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="сокращение"
                    ),
                ),
                (
                    "weekly_hours",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="часов в неделю"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="порядок"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="journal.academicyear",
                        verbose_name="учебный год",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "предмет",
                "verbose_name_plural": "предметы",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="ModuleResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="сумма баллов",
                    ),
                ),
                (
                    "planned_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="распределено баллов",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("failed", "незачёт"),
                            ("base", "базовый уровень"),
                            ("elevated", "повышенный уровень"),
                            ("advanced", "продвинутый уровень"),
                        ],
                        default="failed",
                        max_length=20,
                        verbose_name="уровень",
                    ),
                ),
                ("is_passed", models.BooleanField(default=False, verbose_name="зачёт")),
                (
                    "gap_to_next_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="не хватает до следующего уровня",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="пересчитано"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_results",
                        to="journal.module",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_results",
                        to="journal.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_results",
                        to="journal.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "итог модуля",
                "verbose_name_plural": "итоги модулей",
                "ordering": ["module__starts_on", "subject__position"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="journal.subject",
            ),
        ),
        migrations.AddField(
            model_name="gradeitem",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_items",
                to="journal.subject",
            ),
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("academic", "академическая цель"),
                            ("personal", "личная цель"),
                            ("outcome", "цель-результат"),
                        ],
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("open", "открытая"), ("hidden", "скрытая")],
                        default="open",
                        max_length=10,
                        verbose_name="видимость",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="цель")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "в работе"),
                            ("done", "достигнута"),
                            ("dropped", "снята"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="срок"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="journal.module",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="journal.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="journal.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "цель",
                "verbose_name_plural": "цели",
                "ordering": ["target_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="ставка за час, ₽",
                    ),
                ),
                (
                    "public_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="подпись для сайта"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="journal.subject",
                        verbose_name="предметы",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="учётная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "педагог",
                "verbose_name_plural": "педагоги",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="journal.teacher",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("organization", "title"), name="academic_year_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradingscale",
            constraint=models.UniqueConstraint(
                fields=("organization", "academic_year", "name"),
                name="grading_scale_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["organization", "starts_on", "ends_on"],
                name="journal_mod_organiz_66d158_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("organization", "academic_year", "kind", "number"),
                name="module_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["organization", "status"], name="journal_stu_organiz_8bb8ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["organization", "last_name", "first_name"],
                name="journal_stu_organiz_371691_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "student", "-period_start"],
                name="journal_pay_organiz_12fe3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "status"], name="journal_pay_organiz_bc3c4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moodentry",
            index=models.Index(
                fields=["organization", "student", "-day"],
                name="journal_moo_organiz_f5c386_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="moodentry",
            constraint=models.UniqueConstraint(
                fields=("student", "day"), name="mood_entry_unique_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["organization", "group"], name="journal_gro_organiz_6b95ac_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "student"), name="group_membership_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("organization", "academic_year", "name"), name="group_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["organization", "student"],
                name="journal_gra_organiz_b2ed58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["organization", "grade_item"],
                name="journal_gra_organiz_e45b4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["organization", "-graded_at"],
                name="journal_gra_organiz_b54ea7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("student", "grade_item"),
                name="grade_unique_per_item",
            ),
        ),
        migrations.AddIndex(
            model_name="studentparent",
            index=models.Index(
                fields=["organization", "student"],
                name="journal_stu_organiz_82ec07_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentparent",
            constraint=models.UniqueConstraint(
                fields=("student", "parent"), name="student_parent_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["organization", "last_name"],
                name="journal_par_organiz_d1b13f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["organization", "academic_year"],
                name="journal_sub_organiz_14ea91_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("organization", "academic_year", "name"), name="subject_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="moduleresult",
            index=models.Index(
                fields=["organization", "student", "module"],
                name="journal_mod_organiz_16cd1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moduleresult",
            index=models.Index(
                fields=["organization", "module", "subject"],
                name="journal_mod_organiz_359a3d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleresult",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "module"), name="module_result_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="gradeitem",
            index=models.Index(
                fields=["organization", "module", "subject", "group"],
                name="journal_gra_organiz_8d6750_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_points__gt", 0)),
                name="grade_item_positive_max",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["organization", "student", "visibility"],
                name="journal_goa_organiz_e6f420_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["organization", "student", "kind"],
                name="journal_goa_organiz_a1ac7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["organization", "starts_at"],
                name="journal_les_organiz_683d3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["organization", "group", "starts_at"],
                name="journal_les_organiz_78a6f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["organization", "teacher", "starts_at"],
                name="journal_les_organiz_2fa536_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["organization", "module", "subject"],
                name="journal_les_organiz_eac864_idx",
            ),
        ),
    ]
