# Generated by Django 5.2.17 on 2026-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="kind",
            field=models.CharField(
                choices=[
                    ("academic", "учебный предмет"),
                    ("activity", "блок дня без баллов"),
                ],
                default="academic",
                max_length=10,
                verbose_name="тип",
            ),
        ),
    ]
