# Generated by Django 5.2.17 on 2026-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_subject_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="bio",
            field=models.TextField(blank=True, verbose_name="о педагоге"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="experience",
            field=models.CharField(blank=True, max_length=200, verbose_name="опыт"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Один человек на главной показывается большим блоком.",
                verbose_name="крупная карточка",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Пока выключено, педагог виден только в кабинете.",
                verbose_name="показывать на сайте",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="teachers/", verbose_name="фотография"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="public_position",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="порядок на сайте"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject_line",
            field=models.CharField(
                blank=True,
                help_text="Если пусто, соберётся из списка предметов.",
                max_length=120,
                verbose_name="предметы для сайта",
            ),
        ),
    ]
