# Generated by Django 5.2.17 on 2026-08-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_teacher_cards_into_teachers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="public_title",
        ),
    ]
