# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_auditlog_action"),
        ("journal", "0005_remove_teacher_public_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(verbose_name="задание")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="сдать до"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто задал",
                    ),
                ),
                (
                    "grade_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework",
                        to="journal.gradeitem",
                        verbose_name="оценивание",
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework",
                        to="journal.lesson",
                        verbose_name="занятие",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "домашнее задание",
                "verbose_name_plural": "домашние задания",
                "ordering": ["-lesson__starts_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "due_date"],
                        name="journal_hom_organiz_9bc819_idx",
                    )
                ],
            },
        ),
    ]
