# Generated by Django 5.2.17 on 2026-08-31 10:14

import apps.core.storage
import apps.journal.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_auditlog_action"),
        ("journal", "0006_homework"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.private_storage,
                upload_to=apps.journal.models.homework_photo_path,
                verbose_name="фото листа с задачами",
            ),
        ),
        migrations.CreateModel(
            name="HomeworkMark",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="journal.homework",
                        verbose_name="задание",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_marks",
                        to="journal.student",
                        verbose_name="ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "отметка о выполнении",
                "verbose_name_plural": "отметки о выполнении",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("homework", "student"),
                        name="uniq_homework_mark_per_student",
                    )
                ],
            },
        ),
    ]
