# Generated by Django 5.2.17 on 2026-08-31 11:22

import apps.core.storage
import apps.journal.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_auditlog_action"),
        ("journal", "0007_homework_photo_homeworkmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThematicPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="название"
                    ),
                ),
                (
                    "source",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.core.storage.private_storage,
                        upload_to=apps.journal.models.thematic_plan_path,
                        verbose_name="исходный файл",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="имя файла"
                    ),
                ),
                (
                    "header_row",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="строка заголовка"
                    ),
                ),
                (
                    "column_map",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="разметка колонок"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="примечание")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thematic_plans",
                        to="journal.academicyear",
                        verbose_name="учебный год",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — план общий для всех групп, где идёт предмет.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thematic_plans",
                        to="journal.group",
                        verbose_name="группа",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thematic_plans",
                        to="journal.subject",
                        verbose_name="предмет",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thematic_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "тематическое планирование",
                "verbose_name_plural": "тематические планирования",
                "ordering": ["subject__name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThematicPlanEntry",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="№ по плану"
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата по плану"
                    ),
                ),
                ("topic", models.CharField(max_length=250, verbose_name="тема")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=4,
                        verbose_name="часов",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="тип занятия"
                    ),
                ),
                (
                    "homework",
                    models.TextField(blank=True, verbose_name="домашнее задание"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="примечание")),
                (
                    "is_section",
                    models.BooleanField(
                        default=False, verbose_name="заголовок раздела"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_entries",
                        to="journal.lesson",
                        verbose_name="занятие",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="journal.thematicplan",
                        verbose_name="план",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка планирования",
                "verbose_name_plural": "строки планирования",
                "ordering": ["plan", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="thematicplan",
            index=models.Index(
                fields=["organization", "academic_year", "subject"],
                name="journal_the_organiz_f20ef6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="thematicplanentry",
            index=models.Index(
                fields=["organization", "plan", "position"],
                name="journal_the_organiz_9e290d_idx",
            ),
        ),
    ]
