# Generated by Django 5.2.17 on 2026-08-31 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_auditlog_action"),
        ("journal", "0008_thematicplan_thematicplanentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hero",
            field=models.CharField(
                choices=[
                    ("traveller", "Путник"),
                    ("star", "Звёздочка"),
                    ("compass", "Компас"),
                    ("rocket", "Ракета"),
                ],
                default="traveller",
                max_length=20,
                verbose_name="спутник на пути к цели",
            ),
        ),
        migrations.CreateModel(
            name="GoalStep",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="шаг")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "done_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="сделан"),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="journal.goal",
                        verbose_name="цель",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "шаг к цели",
                "verbose_name_plural": "шаги к цели",
                "ordering": ["position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "goal", "position"],
                        name="journal_goa_organiz_497760_idx",
                    )
                ],
            },
        ),
    ]
