# Generated by Django 5.2.17 on 2026-09-02 08:05

from decimal import Decimal
from decimal import Decimal

from django.db import migrations, models



OLD = {
    "pass_from": Decimal("60.00"),
    "base_from": Decimal("60.00"),
    "elevated_from": Decimal("70.00"),
    "advanced_from": Decimal("80.00"),
}
NEW = {
    "pass_from": Decimal("50.00"),
    "base_from": Decimal("50.00"),
    "elevated_from": Decimal("70.00"),
    "advanced_from": Decimal("85.00"),
}


def adopt_the_regulation(apps, schema_editor):
    """
    Подтянуть шкалы, которых никто не трогал, к регламенту центра.

    Только те, что стоят ровно на прежних значениях по умолчанию: если
    пороги кто-то настраивал руками, это его решение, и переписывать его
    миграцией нельзя.
    """
    GradingScale = apps.get_model("journal", "GradingScale")
    GradingScale.objects.filter(**OLD).update(**NEW)


def back_to_the_old_defaults(apps, schema_editor):
    GradingScale = apps.get_model("journal", "GradingScale")
    GradingScale.objects.filter(**NEW).update(**OLD)


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0009_student_hero_goalstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradingscale",
            name="advanced_from",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("85.00"),
                max_digits=5,
                verbose_name="высокий уровень от",
            ),
        ),
        migrations.AlterField(
            model_name="gradingscale",
            name="base_from",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                max_digits=5,
                verbose_name="базовый уровень от",
            ),
        ),
        migrations.AlterField(
            model_name="gradingscale",
            name="elevated_from",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("70.00"),
                max_digits=5,
                verbose_name="продвинутый уровень от",
            ),
        ),
        migrations.AlterField(
            model_name="gradingscale",
            name="pass_from",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                max_digits=5,
                verbose_name="зачёт от",
            ),
        ),
        migrations.AlterField(
            model_name="moduleresult",
            name="level",
            field=models.CharField(
                choices=[
                    ("failed", "требуется поддержка"),
                    ("base", "базовый"),
                    ("elevated", "продвинутый"),
                    ("advanced", "высокий"),
                ],
                default="failed",
                max_length=20,
                verbose_name="уровень",
            ),
        ),
        migrations.RunPython(adopt_the_regulation, back_to_the_old_defaults),
    ]
