# Generated by Django 5.2.17 on 2026-09-02 09:35

import apps.core.storage
import apps.journal.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models




def photos_become_attachments(apps, schema_editor):
    """
    Перенести уже приложенные фотографии в общий список вложений.

    Сам файл никуда не двигаем: у нового поля то же хранилище, и достаточно
    записать прежний путь. Двигать файлы миграцией — верный способ потерять
    их на первом же сбое.
    """
    import os

    Homework = apps.get_model("journal", "Homework")
    HomeworkFile = apps.get_model("journal", "HomeworkFile")

    for homework in Homework.objects.exclude(photo="").exclude(photo=None):
        # Настоящего имени у прежних снимков нет — поле его не хранило,
        # на диске лежит идентификатор занятия. Показывать ученику
        # «1c2db444-….png» незачем: даём человеческое имя, расширение
        # оставляем, по нему видно, чем открывать.
        suffix = os.path.splitext(homework.photo.name)[1].lower() or ".jpg"
        name = f"Фото листа с задачами{suffix}"
        try:
            size = homework.photo.size
        except (OSError, ValueError):
            # Записи без файла на диске встречаются после переездов.
            size = 0
        HomeworkFile.objects.create(
            organization_id=homework.organization_id,
            homework_id=homework.id,
            file=homework.photo.name,
            name=name,
            size=size,
        )


def attachments_become_photos(apps, schema_editor):
    """
    Обратно — только первая картинка: остальным в одном поле места нет.

    И только та, чей путь в это поле помещается: у вложений он длиннее
    прежнего, а у старого поля сотня символов. Откат — операция аварийная,
    и падать на ней из-за длины пути было бы совсем некстати; что не
    влезло, останется только во вложениях.
    """
    Homework = apps.get_model("journal", "Homework")
    HomeworkFile = apps.get_model("journal", "HomeworkFile")

    for homework in Homework.objects.all():
        first = HomeworkFile.objects.filter(homework_id=homework.id).order_by("created_at").first()
        if first is not None and len(first.file.name) <= 100:
            homework.photo = first.file.name
            homework.save(update_fields=["photo"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_auditlog_action"),
        ("journal", "0010_alter_gradingscale_advanced_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkFile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=apps.core.storage.private_storage,
                        upload_to=apps.journal.models.homework_file_path,
                        verbose_name="файл",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="имя файла")),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="размер, байт"),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="journal.homework",
                        verbose_name="задание",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто приложил",
                    ),
                ),
            ],
            options={
                "verbose_name": "вложение к заданию",
                "verbose_name_plural": "вложения к заданиям",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "homework"],
                        name="journal_hom_organiz_0850ff_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(photos_become_attachments, attachments_become_photos),
        migrations.RemoveField(model_name="homework", name="photo"),
    ]
