# Generated by Django 5.2.17 on 2026-10-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0012_homework_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="удалено"
            ),
        ),
    ]
