# Generated by Django 5.2.17 on 2026-08-25 07:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="имя")),
                (
                    "subject_line",
                    models.CharField(max_length=120, verbose_name="предмет"),
                ),
                (
                    "experience",
                    models.CharField(blank=True, max_length=200, verbose_name="опыт"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="о педагоге")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="teachers/", verbose_name="фото"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="порядок"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликован"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "карточка педагога",
                "verbose_name_plural": "карточки педагогов",
                "ordering": ["position", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                ("question", models.CharField(max_length=250, verbose_name="вопрос")),
                ("answer", models.TextField(verbose_name="ответ")),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="порядок"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликован"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос FAQ",
                "verbose_name_plural": "вопросы FAQ",
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_published", "position"],
                        name="site_public_organiz_336e57_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="удалено"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="имя")),
                ("phone", models.CharField(max_length=16, verbose_name="телефон")),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(11),
                        ],
                        verbose_name="класс ребёнка",
                    ),
                ),
                (
                    "call_window",
                    models.CharField(
                        choices=[
                            ("09-12", "9:00–12:00"),
                            ("12-15", "12:00–15:00"),
                            ("15-18", "15:00–18:00"),
                            ("18-21", "18:00–21:00"),
                        ],
                        max_length=10,
                        verbose_name="удобное время звонка",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("self_study", "ушёл на самообразование"),
                            ("exams", "готовится к ОГЭ или ЕГЭ"),
                            ("career", "не выбрал направление"),
                        ],
                        max_length=20,
                        verbose_name="сегмент",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="комментарий"
                    ),
                ),
                (
                    "consent_at",
                    models.DateTimeField(verbose_name="согласие на обработку ПДн"),
                ),
                (
                    "policy_version",
                    models.CharField(max_length=32, verbose_name="версия политики"),
                ),
                ("utm_source", models.CharField(blank=True, max_length=120)),
                ("utm_medium", models.CharField(blank=True, max_length=120)),
                ("utm_campaign", models.CharField(blank=True, max_length=120)),
                ("utm_content", models.CharField(blank=True, max_length=120)),
                ("utm_term", models.CharField(blank=True, max_length=120)),
                (
                    "referrer",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="реферер"
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="страница"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="user-agent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "новая"),
                            ("diagnostic_scheduled", "диагностика назначена"),
                            ("diagnostic_done", "диагностика проведена"),
                            ("contract", "договор"),
                            ("enrolled", "учится"),
                            ("declined", "отказ"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=24,
                        verbose_name="статус",
                    ),
                ),
                (
                    "decline_reason",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="причина отказа"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="статус изменён"
                    ),
                ),
                (
                    "manager_note",
                    models.TextField(blank=True, verbose_name="заметка администратора"),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="уведомление отправлено"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-created_at"],
                        name="site_public_organiz_5015c7_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="site_public_organiz_4808cf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("privacy", "политика обработки персональных данных"),
                            ("consent", "согласие на обработку персональных данных"),
                            ("terms", "пользовательское соглашение"),
                        ],
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                (
                    "body",
                    models.TextField(
                        verbose_name="текст (Markdown-подобный простой текст)"
                    ),
                ),
                ("version", models.CharField(max_length=32, verbose_name="версия")),
                (
                    "edited_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="дата редакции",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "правовой документ",
                "verbose_name_plural": "правовые документы",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "kind"), name="legal_document_unique"
                    )
                ],
            },
        ),
    ]
