# Generated by Django 5.2.17 on 2026-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_public", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachercard",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Показывается на главной большим блоком с полным текстом. Остальные — компактной лентой: педагогов со временем станет больше, и одинаковых карточек в ряд будет не разглядеть.",
                verbose_name="крупная карточка",
            ),
        ),
    ]
