# Generated by Django 5.2.17 on 2026-08-26 18:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_organization_schedule_url"),
        ("journal", "0002_subject_kind"),
        ("site_public", "0002_teachercard_is_featured"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherReview",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="подпись"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                ("text", models.TextField(max_length=2000, verbose_name="отзыв")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "на проверке"),
                            ("published", "опубликован"),
                            ("rejected", "отклонён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="проверен"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто проверил",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="journal.teacher",
                        verbose_name="педагог",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв о педагоге",
                "verbose_name_plural": "отзывы о педагогах",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "teacher", "status"],
                        name="site_public_organiz_ea8326_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("author__isnull", False)),
                        fields=("teacher", "author"),
                        name="teacher_review_one_per_author",
                    )
                ],
            },
        ),
    ]
