# Generated by Django 5.2.17 on 2026-08-25 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("email", "Email")],
                        max_length=20,
                        verbose_name="канал",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(max_length=200, verbose_name="получатель"),
                ),
                ("kind", models.CharField(max_length=60, verbose_name="тип")),
                (
                    "subject_type",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="тип объекта"
                    ),
                ),
                (
                    "subject_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="id объекта"
                    ),
                ),
                ("body", models.TextField(verbose_name="текст")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "в очереди"),
                            ("sent", "отправлено"),
                            ("failed", "не отправлено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="статус",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="попыток"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="последняя ошибка"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="отправлено"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-created_at"],
                        name="notificatio_organiz_83efba_idx",
                    ),
                    models.Index(
                        fields=["subject_type", "subject_id"],
                        name="notificatio_subject_536c14_idx",
                    ),
                ],
            },
        ),
    ]
